### ISSUE TITLE
When gtid_set is blank binlog_reader fails to start

### ISSUE THREAD

**Issue by pondix** [sysown/proxysql_mysqlbinlog#7]
If no GTIDs have been generated the binlog reader will fail to start with a message `error in initializing slave: basic_string::erase` in the logs.

```
mysql> show master status\G
*************************** 1. row ***************************
             File: mysql-bin.000007
         Position: 154
     Binlog_Do_DB: 
 Binlog_Ignore_DB: 
Executed_Gtid_Set: 
```

Once a GTID has been generated the binary will start as expected. Either the binlog reader should handle this condition or the error message should be made clearer.
